# Generated by Django 3.1.2 on 2023-03-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('commentaire', models.TextField(default='default.text')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Eglise_jacques_christophe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('commentaire', models.TextField(default='default.text')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Jeune_18_35',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('commentaire', models.TextField(default='default.text')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Les_soeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('commentaire', models.TextField(default='default.text')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sacre_coeur_bois_gaumont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('commentaire', models.TextField(default='default.text')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
    ]
