# Generated by Django 3.1.2 on 2023-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eglise_jacques_christophe',
            name='commentaire',
            field=models.TextField(default='NULL'),
        ),
    ]
