# Generated by Django 3.1.2 on 2023-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0004_auto_20230304_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueil',
            name='commentaire',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='jeune_18_35',
            name='commentaire',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='les_soeurs',
            name='commentaire',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='sacre_coeur_bois_gaumont',
            name='commentaire',
            field=models.TextField(default='NULL'),
        ),
    ]
